spring:
  application:
    name: datemate
  datasource:
    url: {PRIVATE}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: {PRIVATE}
      password: {PRIVATE}
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
security:
  oauth2:
    jwt:
      signKey: {PRIVATE}

server:
  port: 8080
  servlet:
    context-path: /datemate

logging:
  level:
    root: info
    web: debug
