spring:
  application:
    name: datemate
  datasource:
    url: jdbc:mariadb://datemate.cjlwtqkaztco.us-east-1.rds.amazonaws.com:3306/datemate
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      username: bjkang
      password: roqkf2015$
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
security:
  oauth2:
    jwt:
      signKey: ssu
#    resource:
#      token-info-uri: http://localhost:8080/oauth/check_token
#    client:
#      client-id: datemate
#      client-secret: ssu

server:
  port: 8080
  servlet:
    context-path: /datemate

logging:
  level:
    root: info
    web: debug
